# Generated by Django 2.2.13 on 2022-03-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220305_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
