# Generated by Django 2.2.13 on 2022-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220306_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='model',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
