# Generated by Django 2.2.13 on 2022-03-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220312_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
