# Generated by Django 2.2.13 on 2022-03-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220312_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='api.OrderProduct', to='api.Product'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='products',
            field=models.ManyToManyField(related_name='parameters', through='api.ProductParameter', to='api.ProductInfo'),
        ),
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(related_name='products', through='api.ProductInfo', to='api.Shop'),
        ),
    ]
